"""Test Scheduler diagnostics."""
from homeassistant.core import HomeAssistant

from custom_components.scheduler.diagnostics import async_get_config_entry_diagnostics


async def test_diagnostics(hass: HomeAssistant, hub_entry):
    """Test diagnostics."""
    hub_entry.add_to_hass(hass)
    await hass.config_entries.async_setup(hub_entry.entry_id)
    await hass.async_block_till_done()

    diagnostics = await async_get_config_entry_diagnostics(hass, hub_entry)

    assert diagnostics["entry"]["entry_id"] == hub_entry.entry_id
    assert diagnostics["entry"]["title"] == "Scheduler"
    assert diagnostics["schedule_count"] == 1
    assert "test_schedule_1" in diagnostics["schedules"]
    assert diagnostics["schedules"]["test_schedule_1"]["name"] == "Test Schedule"


async def test_diagnostics_empty_hub(hass: HomeAssistant, empty_hub_entry):
    """Test diagnostics with empty hub."""
    empty_hub_entry.add_to_hass(hass)
    await hass.config_entries.async_setup(empty_hub_entry.entry_id)
    await hass.async_block_till_done()

    diagnostics = await async_get_config_entry_diagnostics(hass, empty_hub_entry)

    assert diagnostics["entry"]["entry_id"] == empty_hub_entry.entry_id
    assert diagnostics["schedule_count"] == 0
    assert diagnostics["schedules"] == {}
    assert diagnostics["hub_sensor"] is None  # No hub sensor when no schedules


async def test_diagnostics_with_entity_states(hass: HomeAssistant, hub_entry):
    """Test diagnostics includes entity states."""
    hub_entry.add_to_hass(hass)
    await hass.config_entries.async_setup(hub_entry.entry_id)
    await hass.async_block_till_done()

    diagnostics = await async_get_config_entry_diagnostics(hass, hub_entry)

    # Check that entity states are captured
    assert "entity_states" in diagnostics
    assert "test_schedule_1" in diagnostics["entity_states"]
    
    entity_state = diagnostics["entity_states"]["test_schedule_1"]
    assert "entity_id" in entity_state
    assert "state" in entity_state
    assert "attributes" in entity_state
    
    # Check hub sensor info
    assert diagnostics["hub_sensor"] is not None
    assert "entity_id" in diagnostics["hub_sensor"]
    # Entity ID is auto-generated by HA, just verify it exists
    assert diagnostics["hub_sensor"]["entity_id"].startswith("binary_sensor.")
